### PR TITLE
Fix stripping literals, actions, and symbolic actions

### PR DESCRIPTION
**Pull request by KarlSchimpf**
Fixes the following problems with cast2casm (and their corresponding boot implementations):

(1) The code to strip literals was broken due to recent changes that separated symbolic names for literals and callback actions. Fix PR fixes these issues.

(2) The strip-actions flags was not being used, and hence, was not removing callbacks when requested. Fixed this to call the appropriate function.

(3) The code did not remove the use of symbolic names for callbacks (only the integer values are needed). Therefore, a new command line argument "--strip-symbolic-actions" was added, and corresponding code to replace symbolic callbacks with their corresponding integer value.

Note: The advantage of removing symbolic callbacks is a significant reduction in compiled algorithms.

(4) Fixed makefile mistakes where when command line flag "--strip-actions" started working. It was incorrectly applied to the CASM (0x0) algorithms. 

(5) Added some test cases to show that stripping is working.

Note: Did not take advantage of stripping symbolic actions in this PR because we need to refactor the corresponding enumerations generated for the compiled code. Left that for a separate PR.

### CODE REVIEW

**Comment by KarlSchimpf** [comment]
If you get a chance, please take a look. Thanks!

**Comment by binji** [comment]
Sorry, Karl. I took a look yesterday but I had a hard time understanding stuff because I haven't really looked at this code much. :-)

Probably need to just have a "get-up-to-speed" chat so I understand what all the terminology means.

**Comment by KarlSchimpf** [comment]
No problem. When you are free sometime we can meet and chat. (FYI I'm off
thursday thru monday).

Karl Schimpf

**Comment by sbc100** [comment]
Yes, I'd like to be part of that too.

**Pull request merged**
